# Generated by Django 6.1 on 2026-09-19 17:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cities', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AirQuality',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recorded_date', models.DateField()),
                ('aqi', models.IntegerField(help_text='Air Quality Index (0 - 500)')),
                ('pm25', models.FloatField(help_text='PM2.5 concentration in ug/m3')),
                ('pm10', models.FloatField(help_text='PM10 concentration in ug/m3')),
                ('co', models.FloatField(help_text='Carbon Monoxide in mg/m3')),
                ('no2', models.FloatField(help_text='Nitrogen Dioxide in ug/m3')),
                ('so2', models.FloatField(help_text='Sulphur Dioxide in ug/m3')),
                ('o3', models.FloatField(help_text='Ozone in ug/m3')),
                ('traffic_level', models.CharField(choices=[('Low', 'Low'), ('Moderate', 'Moderate'), ('Heavy', 'Heavy'), ('Severe', 'Severe')], default='Moderate', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='air_quality_records', to='cities.city')),
            ],
            options={
                'verbose_name': 'Air Quality Record',
                'verbose_name_plural': 'Air Quality Records',
                'ordering': ['-recorded_date'],
                'unique_together': {('city', 'recorded_date')},
            },
        ),
        migrations.CreateModel(
            name='EnvironmentalAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('environmental_score', models.FloatField(help_text='Calculated Score from 0 to 100')),
                ('risk_level', models.CharField(max_length=50)),
                ('dominant_pollutant', models.CharField(max_length=50)),
                ('recommendation', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('air_quality', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='analysis', to='pollution.airquality')),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analyses', to='cities.city')),
            ],
            options={
                'verbose_name_plural': 'Environmental Analyses',
                'ordering': ['-created_at'],
            },
        ),
    ]
