# Generated by Django 6.1 on 2026-09-19 17:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cities', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Weather',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recorded_date', models.DateField()),
                ('temperature', models.FloatField(help_text='Temperature in degrees Celsius')),
                ('humidity', models.FloatField(help_text='Humidity percentage (0 - 100)')),
                ('rainfall', models.FloatField(default=0.0, help_text='Rainfall in mm')),
                ('wind_speed', models.FloatField(help_text='Wind speed in km/h')),
                ('pressure', models.FloatField(default=1013.25, help_text='Atmospheric pressure in hPa')),
                ('condition', models.CharField(choices=[('Clear', 'Clear / Sunny'), ('Partly Cloudy', 'Partly Cloudy'), ('Cloudy', 'Cloudy'), ('Hazy', 'Hazy / Smog'), ('Rainy', 'Rainy'), ('Thunderstorm', 'Thunderstorm')], default='Clear', max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='weather_records', to='cities.city')),
            ],
            options={
                'verbose_name': 'Weather Record',
                'verbose_name_plural': 'Weather Records',
                'ordering': ['-recorded_date'],
                'unique_together': {('city', 'recorded_date')},
            },
        ),
    ]
